
[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.metadata] 
allow-direct-references = true

[project]
name = "wxutils"
version = "0.0.1"
authors = [
  { name="Marcus Pearlman", email="marcuspearlman@boisestate.edu" },
]
description = "A package containing warpx helper methods"
readme = "README.rst"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

dependencies = [
  "numpy",             # data manipulation
#   "pandas",            # data manipulation
  "matplotlib",        # for plotting
  "h5py",              # for data saving
]

[project.optional-dependencies]

warpx = ["warpx"]  # this is required but the user may install from source.
pyro = ["Pyro5@git+https://github.com/pearlmam/Pyro5.git"]


geoviz = [  
  "trimesh",           
  "shapely",            
  "mapbox-earcut",      
  "scikit-image",   
  ]


[project.scripts]
warpx-dispatch = "wxutils.dispatch:main"


[project.urls]
Homepage = "https://github.com/pearlmam/warpx-helpers/"
Issues = "https://github.com/pearlmam/warpx-helpers/issues"
